"""Output formatters for AIR Editorial Intelligence — Week 11/12.

Converts editorial outputs into human-readable publication formats:

- MarkdownFormatter        : APSA-style Markdown (thematic multi-incident editorial)
- ExcelFormatter           : openpyxl workbook with one sheet per section
- APSANewsletterFormatter  : bundled newsletter Markdown from per-incident APSAArticles

All formatters are stateless.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.insights.editorial_models import APSAArticle, EditorialReport, EditorialSection


# ---------------------------------------------------------------------------
# Markdown — APSA-aligned
# ---------------------------------------------------------------------------


class MarkdownFormatter:
    """Render an EditorialReport as a strict APSA-style Markdown document.

    Format matches the APSA newsletter standard:
      - Evocative journalistic title
      - Case vignette / executive narrative (no section header)
      - Flowing thematic sections (bold title + educational prose)
      - Conclusion paragraph
      - Academic references (or incident evidence if no academic refs available)
      - Minimal footer
    """

    def format(self, report: "EditorialReport") -> str:
        """Return a complete APSA-style Markdown string for the given report."""
        now = datetime.now(timezone.utc).strftime("%B %d, %Y")
        lines: list[str] = []

        # ── Title — evocative headline preferred ────────────────────────────
        display_title = report.evocative_title if report.evocative_title else report.title
        lines += [
            f"# {display_title}",
            "",
            f"**Published:** {now}",
            "",
            "---",
            "",
        ]

        # ── Vignette / executive narrative ───────────────────────────────────
        lines += [report.executive_summary, "", "---", ""]

        # ── Thematic sections — flowing prose, no Key Learning blocks ────────
        for section in report.sections:
            lines += [f"**{section.title}**", "", section.narrative, ""]

        # ── Conclusion ───────────────────────────────────────────────────────
        lines += ["---", "", report.conclusion, "", "---", ""]

        # ── References — academic preferred; incident evidence as fallback ───
        if report.clinical_references:
            lines += ["**References**", ""]
            for ref in report.clinical_references:
                lines.append(ref)
            lines.append("")
        elif report.all_citations:
            lines += ["**Supporting Incident Evidence**", ""]
            for i, citation in enumerate(report.all_citations, 1):
                lines.append(f"{i}. {citation}")
            lines.append("")

        # ── Footer ────────────────────────────────────────────────────────────
        lines += [
            "---",
            "",
            f"*Generated by AIR Clinical Incident Intelligence Engine · {now}*",
        ]

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------


class ExcelFormatter:
    """Render an EditorialReport as an openpyxl workbook returned as bytes."""

    # Maximum characters allowed by Excel for a sheet name
    _MAX_SHEET_NAME = 31

    def format(self, report: "EditorialReport") -> bytes:
        """Return the workbook serialised to raw bytes (suitable for download)."""
        try:
            import openpyxl
        except ImportError as exc:
            raise RuntimeError("openpyxl is required for Excel export") from exc

        wb = openpyxl.Workbook()
        wb.remove(wb.active)  # remove default empty sheet

        self._build_summary_sheet(wb, report)
        for section in report.sections:
            self._build_section_sheet(wb, section)
        if report.all_citations:
            self._build_citations_sheet(wb, report)

        buf = io.BytesIO()
        wb.save(buf)
        buf.seek(0)
        return buf.read()

    # ------------------------------------------------------------------
    # Private sheet builders
    # ------------------------------------------------------------------

    def _build_summary_sheet(self, wb, report: "EditorialReport") -> None:
        ws = wb.create_sheet("Summary")
        ws.append(["Field", "Value"])

        meta_rows = [
            ("Title", report.title),
            ("Query", report.query),
            ("Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")),
            ("Incidents Reviewed", report.total_incidents_referenced),
            ("Sections", report.section_count),
            ("Grounded Sections", report.grounded_section_count),
            ("Tone Score", report.tone_score),
            ("Word Count", report.word_count),
            ("Has LLM Narrative", report.has_llm_narrative),
            ("Model Version", report.model_version),
        ]
        for row in meta_rows:
            ws.append(row)

        ws.append(["", ""])
        ws.append(["Executive Summary", report.executive_summary])
        ws.append(["", ""])
        ws.append(["Conclusion", report.conclusion])

        ws.column_dimensions["A"].width = 22
        ws.column_dimensions["B"].width = 100

    def _build_section_sheet(self, wb, section: "EditorialSection") -> None:
        raw_name = section.theme.replace("_", " ").title()
        # Sanitise illegal Excel sheet-name characters and truncate
        for ch in r"/\?*[]":
            raw_name = raw_name.replace(ch, "")
        sheet_name = raw_name[: self._MAX_SHEET_NAME]

        ws = wb.create_sheet(sheet_name)
        ws.append(["Field", "Value"])

        ws.append(["Theme", section.theme])
        ws.append(["Title", section.title])
        ws.append(["Tone Score", section.tone_score])
        ws.append(["Word Count", section.word_count])
        ws.append(["Is Grounded", section.is_grounded])
        ws.append(["Insight Count", section.insight_count])
        ws.append(["", ""])
        ws.append(["Narrative", section.narrative])
        ws.append(["", ""])
        ws.append(["Key Learning", section.key_learning])

        if section.evidence_citations:
            ws.append(["", ""])
            ws.append(["Evidence Citations", ""])
            for citation in section.evidence_citations:
                ws.append(["", citation])

        ws.column_dimensions["A"].width = 22
        ws.column_dimensions["B"].width = 100

    def _build_citations_sheet(self, wb, report: "EditorialReport") -> None:
        ws = wb.create_sheet("Citations")
        ws.append(["#", "Citation"])
        for i, citation in enumerate(report.all_citations, 1):
            ws.append([i, citation])
        ws.column_dimensions["A"].width = 5
        ws.column_dimensions["B"].width = 110


# ---------------------------------------------------------------------------
# APSA Newsletter — bundles per-incident articles into one document
# ---------------------------------------------------------------------------


class APSANewsletterFormatter:
    """Render a list of APSAArticles as a single APSA newsletter Markdown document."""

    def format(self, articles: "list[APSAArticle]", month: str) -> str:
        """Return a newsletter Markdown document containing all articles.

        Args:
            articles: List of APSAArticle instances (one per top incident).
            month: Edition label, e.g. "2026-06" or "June 2026".

        Returns:
            Complete Markdown string ready for publication.
        """
        now = datetime.now(timezone.utc).strftime("%B %d, %Y")
        lines: list[str] = [
            "# AIR Clinical Incident Intelligence Newsletter",
            "",
            f"**Edition:** {month}  ",
            f"**Published:** {now}  ",
            f"**Articles:** {len(articles)}",
            "",
            "---",
            "",
        ]

        for i, article in enumerate(articles, 1):
            lines += [
                f"## {article.title}",
                "",
                f"*{article.vignette}*",
                "",
            ]
            lines.append(article.body)
            lines.append("")

            if article.clinical_references:
                lines += ["**References**", ""]
                for ref in article.clinical_references:
                    lines.append(ref)
                lines.append("")

            lines += ["---", ""]

        lines += [
            f"*Generated by AIR Clinical Incident Intelligence Engine · {now}*",
            "",
            "*Note: Academic references should be verified before publication.*",
        ]

        return "\n".join(lines)
